### ISSUE TITLE
Running scripts/predict.sh && sh scripts/evaluate.sh produces IndexError: Caught IndexError in replica 1 on device 1

### ISSUE THREAD

**Issue by saraalrawi** [yinkalario/EIN-SELD#3]
After downloading the pre-trained models following the instruction provided in the readme.
I tried to run the following shell command: 

`sh scripts/predict.sh && sh scripts/evaluate.sh
 `
I received the following error: 

  `File "/home/alrawis/EIN-SELD/seld/learning/infer.py", line 23, in infer
    pred = inferer.infer(test_generator)
  File "/home/alrawis/EIN-SELD/seld/methods/ein_seld/inference.py", line 50, in infer
    pred = self.model(batch_x)
  File "/home/alrawis/miniconda3/envs/ein/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/alrawis/miniconda3/envs/ein/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/alrawis/miniconda3/envs/ein/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/alrawis/miniconda3/envs/ein/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/alrawis/miniconda3/envs/ein/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/alrawis/miniconda3/envs/ein/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/alrawis/miniconda3/envs/ein/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/alrawis/EIN-SELD/seld/methods/ein_seld/models/seld.py", line 95, in forward
    x_sed = torch.einsum('c, nctf -> nctf', self.stitch[0][:, 0, 0], x_sed) + \
  File "/home/alrawis/miniconda3/envs/ein/lib/python3.7/site-packages/torch/nn/modules/container.py", line 426, in __getitem__
    idx = self._get_abs_string_index(idx)
  File "/home/alrawis/miniconda3/envs/ein/lib/python3.7/site-packages/torch/nn/modules/container.py", line 409, in _get_abs_string_index
    raise IndexError('index {} is out of range'.format(idx))
IndexError: index 0 is out of range`

My pc has 2 gpus: 

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN X (Pascal)    Off  | 00000000:03:00.0  On |                  N/A |
| 23%   29C    P8    10W / 250W |    145MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN X (Pascal)    Off  | 00000000:04:00.0 Off |                  N/A |
| 23%   31C    P8     9W / 250W |      2MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2753      G   /usr/lib/xorg/Xorg                            57MiB |
|    0      2795      G   /usr/bin/gnome-shell                          84MiB |
+-----------------------------------------------------------------------------+

I appreciate your quick reply.

**Comment by saraalrawi** [comment]
Since I have 2 gpus, the issue solved as follows: 
in seld/utils/common.py 
`model = torch.nn.DataParallel(model,device_ids=[0])` this way you will use the device id=0.

**Comment by yinkalario** [comment]
Ah I forgot to say that some model doesn't work for more than one GPUs. If you use some other models, it might work. It should be a model issue.
