### ISSUE TITLE
missing key(s) in state_dict: "pe.pe".

### ISSUE THREAD

**Issue by modaresimr** [yinkalario/EIN-SELD#5]
I don't have any GPU in my system and I'm facing with this error.
Would you please help me?
```
sh scripts/predict.sh
```
```
Traceback (most recent call last):
  File "seld/main.py", line 59, in <module>
    sys.exit(main(args, cfg))
  File "seld/main.py", line 48, in main
    infer.infer(cfg, dataset, **infer_initializer)
  File "/workspace/sed/EIN-SELD/seld/learning/infer.py", line 20, in infer
    model.module.load_state_dict(state_dict['model'])
  File "/opt/conda/envs/ein/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for EINV2:
        Missing key(s) in state_dict: "pe.pe".
```

**Comment by yinkalario** [comment]
Can you try the code again with a fresh clone of the code? I might have changed something which leads to this error. Not it should be fine. Let me know if it doesn't work. Thanks.

**Comment by modaresimr** [comment]
Thanks for your response.
The issue has been fixed by i have faced with [another issue](https://github.com/yinkalario/EIN-SELD/issues/6) 
Therefore I can not test it.
